name: Stock Prediction Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Análisis exploratorio
      - name: Run Exploratory Analysis
        run: |
          python scripts/01_analisis_exploratorio.py

      # Preprocesamiento
      - name: Run Preprocessing
        run: |
          python scripts/02_preprocesamiento.py

      # Entrenamiento y validación
      - name: Train and Validate Models
        run: |
          python scripts/03_entrenamiento_validacion.py

      # Evaluación final y exportación
      - name: Run Evaluation and Export
        run: |
          python scripts/04_evaluacion_exportacion.py

      # Subir artefactos generados (gráficos, CSVs)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # actualizado a la versión más reciente
        with:
          name: ml-results
          path: |
            *.csv
            *.png
